[package]
name = "promptgen"
version = "0.1.0"
authors = ["lastsecondsave <lastsecondsave@outlook.com>"]
edition = "2018"

[dependencies]
clap = "~2.33.0"

[profile.release]
lto = true
panic = "abort"
